language: node_js
matrix:
  fast_finish: true
node_js:
- 8
env:
  matrix:
  - TESTS_SUITE=tools
  - TESTS_SUITE=cozy-scripts:default
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn lint
- yarn test:$TESTS_SUITE
