language: node_js
node_js:
- 8
cache:
  yarn: true
  directories:
  - node_modules
jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: test
      script: yarn test:tools
    - script: yarn test:cozy-scripts:default
    - stage: deploy
      if: branch = master AND type = push AND fork = false
      script: ./scripts/deploy.sh
